package br.com.trader.esportivo.entradas.domain.model;

public enum PaisEnum {

	AFEGANISTAO("Afeganistão"),
	AFRICA_DO_SUL("África do Sul"),
	ALBANIA("Albânia"),
	ALEMANHA("Alemanha"),
	ANDORRA("Andorra"),
	ANGOLA("Angola"),
	ANTIGA_E_BARBUDA("Antiga e Barbuda"),
	ARABIA_SAUDITA("Arábia Saudita"),
	ARGELIA("Argélia"),
	ARGENTINA("Argentina"),
	ARMENIA("Armênia"),
	AUSTRALIA("Austrália"),
	AUSTRIA("Áustria"),
	AZERBAIJAO("Arzebaijão"),
	BAHAMAS("Bahamas"),
	BANGLADEXE("Bangladexe"),
	BARBADOS("Barbados"),
	BAREM("Barem"),
	BELGICA("Bélgica"),
	BELIZE("Belize"),
	BENIM("Benim"),
	BIELORRUSSIA("Bielorrusia"),
	BOLIVIA("Bolívia"),
	BOSNIA_E_HERZEGOVINA("Bósnia e Herzegovina"),
	BOTSUANA("Botsuana"),
	BRASIL("Brasil"),
	BRUNEI("Brunei"),
	BULGARIA("Bulgária"),
	BURQUINA_FASO("Burquina Faso"),
	BURUNDI("Burundi"),
	BUTAO("Butão"),
	CABO_VERDE("Cabo Verde"),
	CAMAROES("Camarões"),
	CAMBOJA("Camboja"),
	CANADA("Canadá"),
	CATAR("Catar"),
	CAZAQUISTAO("Cazaquistão"),
	CHADE("Chade"),
	CHILE("Chile"),
	CHINA("China"),
	CHIPRE("Chipre"),
	COLOMBIA("Colômbia"),
	COMORES("Comores"),
	CONGO_BRAZZAVILLE("Congo Brazzaville"),
	COREIA_DO_NORTE("Coréia do Norte"),
	COREIA_DO_SUL("Coréia do Sul"),
	COSOVO("Cosovo"),
	COSTA_DO_MARFIM("Costa do Marfim"),
	COSTA_RICA("Costa Rica"),
	CROACIA("Croácia"),
	CUAITE("Cuaite"),
	CUBA("Cuba"),
	DINAMARCA("Dinamarca"),
	DOMINICA("Dominica"),
	EGITO("Égito"),
	EMIRADOS_ARABES_UNIDOS("Emirados Árabes Unidos"),
	EQUADOR("Equador"),
	ERITREIA("Eritreia"),
	ESLOVAQUIA("Eslováquia"),
	ESLOVENIA("Eslovênia"),
	ESPANHA("Espanha"),
	ESSUATINI("Essuatini"),
	ESTADO_DA_PALESTINA("Palestina"),
	ESTADOS_UNIDOS("Estados Unidos"),
	ESTONIA("Estônia"),
	ETIOPIA("Etiópia"),
	FIJI("Fiji"),
	FILIPINAS("Filipinas"),
	FINLANDIA("Finlândia"),
	FRANCA("França"),
	GABAO("Gabão"),
	GAMBIA("Gambia"),
	GANA("Gana"),
	GEORGIA("Geórgia"),
	GRANADA("Granada"),
	GRECIA("Grécia"),
	GUATEMALA("Guatemala"),
	GUIANA("Guiana"),
	GUINE("Guiné"),
	GUINE_EQUATORIAL("Guiné Equatorial"),
	GUINE_BISSAU("Guiné Bissau"),
	HAITI("Haiti"),
	HONDURAS("Honduras"),
	HUNGRIA("Hungria"),
	IEMEN("Iêmen"),
	ILHAS_MARECHAL("Ilhas Marechal"),
	INDIA("Índia"),
	INDONESIA("Indonésia"),
	IRAO("Irão"),
	IRAQUE("Iraque"),
	IRLANDA("Irlanda"),
	ISLANDIA("Islândia"),
	ISRAEL("Israel"),
	ITALIA("Itália"),
	JAMAICA("Jamaica"),
	JAPAO("Japão"),
	JIBUTI("Jibuti"),
	JORDANIA("Jordânia"),
	LAUS("Laus"),
	LESOTO("Lesoto"),
	LETONIA("Letônia"),
	LIBANO("Líbano"),
	LIBERIA("Libéria"),
	LIBIA("Líbia"),
	LISTENSTAINE("Listenstaine"),
	LITUANIA("Lituania"),
	LUXEMBURGO("Luxemburgo"),
	MACEDONIA_DO_NORTE("Macedônia do Norte"),
	MADAGASCAR("Madagascar"),
	MALASIA("Malásia"),
	MALAUI("Malaui"),
	MALDIVAS("Maldivas"),
	MALI("Mali"),
	MALTA("Malta"),
	MARROCOS("Marrocos"),
	MAURICIA("Mauricia"),
	MAURITANIA("Mauritania"),
	MEXICO("México"),
	MIANMAR("Mianmar"),
	MICRONESIA("Micronesia"),
	MOCAMBIQUE("Moçambique"),
	MOLDAVIA("Moldávia"),
	MONACO("Mónaco"),
	MONGOLIA("Mongólia"),
	MONTENEGRO("Montenegro"),
	NAMIBIA("Namibia"),
	NAURU("Nauru"),
	NEPAL("Nepal"),
	NICARAGUA("Nicaragua"),
	NIGER("Níger"),
	NIGERIA("Nigéria"),
	NORUEGA("Noruega"),
	NOVA_ZELANDIA("Nova Zelândia"),
	OMA("Omã"),
	HOLANDA("Holanda"),
	PALAU("Palau"),
	PANAMA("Panamá"),
	PAPUA_NOVA_GUINE("Papua Nova Guiné"),
	PAQUISTAO("Paquistão"),
	PARAGUAI("Paraguai"),
	PERU("Peru"),
	POLONIA("Polônia"),
	PORTUGAL("Portugal"),
	QUENIA("Quênia"),
	QUIRGUISTAO("Quirguistão"),
	QUIRIBATI("Quiribati"),
//	REINO_UNIDO("Reino Unido"),
	INGLATERRA("Inglaterra"),
	IRLANDA_DO_NORTE("Irlanda do Norte"),
	ESCOCIA("Escócia"),
	PAIS_GALES("País de Gales"),
	REPUBLICA_CENTRO_AFRICANA("República Centro Africana"),
	REPUBLICA_CHECA("República Checa"),
	REPUBLICA_DEMOCRATICA_DO_CONGO("República Democrática do Congo"),
	REPUBLICA_DOMINICANA("República Dominicana"),
	ROMENIA("Romênia"),
	RUANDA("Ruanda"),
	RUSSIA("Rússia"),
	SALOMAO("Salomão"),
	SALVADOR("Salvador"),
	SAMOA("Samoa"),
	SANTA_LUCIA("Santa Lúcia"),
	SAO_CRISTOVAO_E_NEVES("São Cristovão e Neves"),
	SAO_MARINHO("São Marinho"),
	SAO_TOME_E_PRINCIPE("São Tomé e Príncipe"),
	SAO_VICENTE_E_GRANADINAS("São Vicente e Granadinas"),
	SEICHELES("Seicheles"),
	SENEGAL("Senegal"),
	SERRA_LEOA("Serra Leõa"),
	SERVIA("Sérvia"),
	SINGAPURA("Singapura"),
	SIRIA("Síria"),
	SOMALIA("Somália"),
	SRI_LANCA("Sri Lanca"),
	SUDAO("Sudão"),
	SUDAO_DO_SUL("Sudão do Sul"),
	SUECIA("Suécia"),
	SUICA("Suíça"),
	SURINAME("Suriname"),
	TAILANDIA("Tailândia"),
	TAIUA("Taiua"),
	TAJIQUISTAO("Tajiquistão"),
	TANZANIA("Tanzânia"),
	TIMOR_LESTE("Timor Leste"),
	TOGO("Togo"),
	TONGA("Tonga"),
	TRINDADE_E_TOBAGO("Trindade e Tobago"),
	TUNISIA("Tunísia"),
	TURCOMENISTAO("Turcomenistão"),
	TURQUIA("Turquia"),
	TUVALU("Tuvalu"),
	UCRANIA("Ucrânia"),
	UGANDA("Uganda"),
	URUGUAI("Uruguai"),
	USBEQUISTAO("Usbequistão"),
	VANUATU("Vanuatu"),
	VENEZUELA("Venezuela"),
	VIETNAME("Vietname"),
	ZAMBIA("Zâmbia"),
	ZIMBABUE("Zimbabue");
	
	private String label;
	
	PaisEnum(String label) {
		this.label = label;
	}

	public String getLabel() {
		return label;
	}
	
}
