CREATE TABLE METODO (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    stake_default DECIMAL(19,2),
    id_banca BIGINT NOT NULL,
    
    FOREIGN KEY (id_banca) REFERENCES BANCA(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;