CREATE TABLE APORTE_SAQUE (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
    id_banca BIGINT  NOT NULL,
	saque_aporte DECIMAL(19,2) NOT NULL,
    
    FOREIGN KEY (id_banca) REFERENCES BANCA(id)    
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;