insert into CAMPEONATO (id, nome, pais_enum, continente_enum, total_times, data_atualizacao, ativo)  values (1, 'Premier League', 'INGLATERRA', 'EUROPA', 20, utc_timestamp, 1);
insert into CAMPEONATO (id, nome, pais_enum, continente_enum, total_times, data_atualizacao, ativo)  values (2, 'Bundesliga', 'ALEMANHA', 'EUROPA', 18, utc_timestamp, 0);
insert into CAMPEONATO (id, nome, pais_enum, continente_enum, total_times, data_atualizacao, ativo)  values (3, 'Eredivisie', 'HOLANDA', 'EUROPA', 18, utc_timestamp, 0);
insert into CAMPEONATO (id, nome, data_atualizacao)  values (4, 'Amistoso', utc_timestamp);
insert into CAMPEONATO (id, nome, data_atualizacao, pais_enum, continente_enum)  values (5, 'Brasileirão Série A', utc_timestamp, 'BRASIL', 'AMERICA');
insert into CAMPEONATO (id, nome, data_atualizacao, pais_enum, continente_enum)  values (6, 'La Liga', utc_timestamp, 'ESPANHA', 'EUROPA');
insert into CAMPEONATO (id, nome, data_atualizacao, pais_enum, continente_enum)  values (7, 'Série A', utc_timestamp, 'ITALIA', 'EUROPA');
insert into CAMPEONATO (id, nome, data_atualizacao, pais_enum, continente_enum)  values (8, 'Primeira Liga', utc_timestamp, 'PORTUGAL', 'EUROPA');
insert into CAMPEONATO (id, nome, data_atualizacao, pais_enum, continente_enum)  values (9, 'Pro League', utc_timestamp, 'BELGICA', 'EUROPA');
insert into CAMPEONATO (id, nome, data_atualizacao, continente_enum)  values (10, 'Europa League', utc_timestamp, 'EUROPA');
insert into CAMPEONATO (id, nome, data_atualizacao, continente_enum)  values (11, 'Conferece League', utc_timestamp, 'EUROPA');
insert into CAMPEONATO (id, nome, data_atualizacao, pais_enum, continente_enum)  values (12, 'Brasileirão Série B', utc_timestamp, 'BRASIL', 'AMERICA');
insert into CAMPEONATO (id, nome, pais_enum, continente_enum, total_times, data_atualizacao, ativo)  values (13, 'Bundesliga 2', 'ALEMANHA', 'EUROPA', 18, utc_timestamp, 0);
insert into CAMPEONATO (id, nome, data_atualizacao, pais_enum, continente_enum)  values (14, 'La Liga 2', utc_timestamp, 'ESPANHA', 'EUROPA');
insert into CAMPEONATO (id, nome, data_atualizacao, pais_enum, continente_enum)  values (15, 'Super Lig', utc_timestamp, 'TURQUIA', 'EUROPA');
insert into CAMPEONATO (id, nome, data_atualizacao)  values (16, 'Mundial de Clubes', utc_timestamp);
insert into CAMPEONATO (id, nome, data_atualizacao, pais_enum, continente_enum)  values (17, 'Copa do Brasil', utc_timestamp, 'BRASIL', 'AMERICA');
insert into CAMPEONATO (id, nome, data_atualizacao, pais_enum, continente_enum)  values (18, 'Pokal', utc_timestamp, 'ALEMANHA', 'EUROPA');
insert into CAMPEONATO (id, nome, data_atualizacao, pais_enum)  values (19, 'FA Cup', utc_timestamp, 'INGLATERRA');
insert into CAMPEONATO (id, nome, pais_enum, continente_enum, data_atualizacao, ativo)  values (20, 'Ligue 1', 'FRANCA', 'EUROPA', utc_timestamp, 0);
insert into CAMPEONATO (id, nome, pais_enum, continente_enum, data_atualizacao, ativo)  values (21, 'Bundesliga Áustria', 'AUSTRIA', 'EUROPA', utc_timestamp, 0);
insert into CAMPEONATO (id, nome, pais_enum, continente_enum, data_atualizacao, ativo)  values (22, 'Fortuna Liga', 'REPUBLICA_CHECA', 'EUROPA', utc_timestamp, 0);
insert into CAMPEONATO (id, nome, pais_enum, continente_enum, data_atualizacao, ativo)  values (23, 'Premier League Israel', 'ISRAEL', 'EUROPA', utc_timestamp, 0);
insert into CAMPEONATO (id, nome, pais_enum, continente_enum, data_atualizacao, ativo)  values (24, 'Eliteserien', 'NORUEGA', 'EUROPA', utc_timestamp, 0);
insert into CAMPEONATO (id, nome, pais_enum, continente_enum, data_atualizacao, ativo)  values (25, 'Superliga Romênia', 'ROMENIA', 'EUROPA', utc_timestamp, 0);
insert into CAMPEONATO (id, nome, pais_enum, continente_enum, data_atualizacao, ativo)  values (26, 'Saudi Pro League', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp, 0);
insert into CAMPEONATO (id, nome, pais_enum, continente_enum, data_atualizacao, ativo)  values (27, 'Premiership', 'ESCOCIA', 'EUROPA', utc_timestamp, 0);
insert into CAMPEONATO (id, nome, pais_enum, continente_enum, data_atualizacao, ativo)  values (28, 'Mozzart Bet Superliga', 'SERVIA', 'EUROPA', utc_timestamp, 0);

insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (1, 'Ajax', 'HOLANDA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (2, 'Feyenoord', 'HOLANDA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (3, 'AZ Alkmaar', 'HOLANDA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (4, 'PSV Eindhoven', 'HOLANDA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (5, 'FC Twente', 'HOLANDA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (6, 'Sparta Rotterdam', 'HOLANDA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (7, 'FC Utrecht', 'HOLANDA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (8, 'RKC Waalwijk', 'HOLANDA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (9, 'NEC Nijmegen', 'HOLANDA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (10, 'Heerenveen', 'HOLANDA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (11, 'Fortuna Sittard', 'HOLANDA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (12, 'Go Ahead Eagles', 'HOLANDA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (13, 'Vitesse', 'HOLANDA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (14, 'FC Volendam', 'HOLANDA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (15, 'FC Emmen', 'HOLANDA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (16, 'Excelsior', 'HOLANDA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (17, 'FC Groningen', 'HOLANDA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (18, 'SC Cambuur', 'HOLANDA', 'EUROPA', utc_timestamp);

insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (19, 'Arsenal', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (20, 'Manchester City', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (21, 'Manchester United', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (22, 'Tottenham', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (23, 'Newcastle', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (24, 'Liverpool', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (25, 'Brighton & Hove Albion', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (26, 'Fulham', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (27, 'Brentford', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (28, 'Chelsea', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (29, 'Aston Villa', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (30, 'Crystal Palace', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (31, 'Wolverhampton', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (32, 'Nottingham Forest', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (33, 'Everton', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (34, 'Leicester City', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (35, 'West Ham', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (36, 'Bournemouth', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (37, 'Leeds United', 'INGLATERRA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (38, 'Southampton', 'INGLATERRA', 'EUROPA', utc_timestamp);
                                                      
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (39, 'Augsburg', 'ALEMANHA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (40, 'Bayer Leverkusen', 'ALEMANHA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (41, 'Bayern de Munique', 'ALEMANHA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (42, 'Bochum', 'ALEMANHA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (43, 'Borussia Dortmund', 'ALEMANHA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (44, 'Borussia M\'gladbach', 'ALEMANHA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (45, 'Eintracht Frankfurt', 'ALEMANHA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (46, 'Freiburg', 'ALEMANHA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (47, 'Hertha Berlin', 'ALEMANHA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (48, 'Hoffenheim', 'ALEMANHA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (49, 'Köln', 'ALEMANHA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (50, 'Mainz 05', 'ALEMANHA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (51, 'RB Leipzig', 'ALEMANHA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (52, 'Schalke 04', 'ALEMANHA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (53, 'Stuttgart', 'ALEMANHA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (54, 'Union Berlin', 'ALEMANHA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (55, 'Werder Bremen', 'ALEMANHA', 'EUROPA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (56, 'Wolfsburg', 'ALEMANHA', 'EUROPA', utc_timestamp);

insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (57, 'Zwolle', 'HOLANDA', 'EUROPA', utc_timestamp);

insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (58, 'Athletico-PR', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (59, 'Atlético-GO', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (60, 'Atlético-MG', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (61, 'Bahia', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (62, 'Botafogo', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (63, 'Bragantino', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (64, 'Corinthians', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (65, 'Criciúma', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (66, 'Cruzeiro', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (67, 'Cuiabá', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (68, 'Flamengo', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (69, 'Fluminense', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (70, 'Fortaleza', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (71, 'Grêmio', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (72, 'Internacional', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (73, 'Juventude', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (74, 'Palmeiras', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (75, 'São Paulo', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (76, 'Vasco', 'BRASIL', 'AMERICA', utc_timestamp);
insert into TIME (id, nome, pais_enum, continente_enum, data_atualizacao)  values (77, 'Vitória', 'BRASIL', 'AMERICA', utc_timestamp);

insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Real Madrid', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Barcelona', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Girona', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Atlético de Madrid', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Athletic Bilbao', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Real Sociedad', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Valencia', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Betis', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Osasuna', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Villarreal', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Getafe', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Las Palmas', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Alavés', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Sevilla', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Mallorca', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Rayo Vallecano', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Celta', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Cádiz', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Granada', 'ESPANHA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Almería', 'ESPANHA', 'EUROPA', utc_timestamp);

insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Inter', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Milan', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Juventus', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Bologna', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Roma', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Atalanta', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Napoli', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Lazio', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Torino', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Fiorentina', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Monza', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Genoa', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Cagliari', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Lecce', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Udinese', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Empoli', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Hellas Verona', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Frosinone', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Sassuolo', 'ITALIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Salernitana', 'ITALIA', 'EUROPA', utc_timestamp);

insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Sporting', 'PORTUGAL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Benfica', 'PORTUGAL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('FC Porto', 'PORTUGAL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Braga', 'PORTUGAL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Vitória SC', 'PORTUGAL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Moreirense', 'PORTUGAL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Arouca', 'PORTUGAL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Famalicao', 'PORTUGAL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Casa Pia', 'PORTUGAL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Farense', 'PORTUGAL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Boavista', 'PORTUGAL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Rio Ave', 'PORTUGAL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Estoril', 'PORTUGAL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Gil Vicente', 'PORTUGAL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Estrela', 'PORTUGAL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Portimonense', 'PORTUGAL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Vizela', 'PORTUGAL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Chaves', 'PORTUGAL', 'EUROPA', utc_timestamp);

insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Royale Union SG', 'BELGICA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Anderlecht', 'BELGICA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Antwerp', 'BELGICA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Club Brugge', 'BELGICA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Cercle Brugge', 'BELGICA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Genk', 'BELGICA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Gent', 'BELGICA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('KV Mechelen', 'BELGICA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('St. Truiden', 'BELGICA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('St. Liege', 'BELGICA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Westerlo', 'BELGICA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Leuven', 'BELGICA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Charleroi', 'BELGICA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Eupen', 'BELGICA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Kortrijk', 'BELGICA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Molembeek', 'BELGICA', 'EUROPA', utc_timestamp);

insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Galatasaray', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Fenerbahce', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Trabzonspor', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Besiktas', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Kasimpasa', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Rizespor', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Basaksehir', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Antalyaspor', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Alanyaspor', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Sivasspor', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Adana Demirspor', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Samsunspor', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Kayserispor', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Ankaragucu', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Hatayspor', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Konyaspor', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Gaziantep', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Karagumruk', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Pendikspor', 'TURQUIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Istanbulspor', 'TURQUIA', 'EUROPA', utc_timestamp);

insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('PSG', 'FRANCA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Brest', 'FRANCA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Monaco', 'FRANCA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Lille', 'FRANCA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Nice', 'FRANCA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Lens', 'FRANCA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Reims', 'FRANCA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Olympique de Marselha', 'FRANCA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Rennes', 'FRANCA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Lyon', 'FRANCA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Toulouse', 'FRANCA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Strasbourg', 'FRANCA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Montpellier', 'FRANCA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Le Havre', 'FRANCA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Nantes', 'FRANCA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Lorient', 'FRANCA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Metz', 'FRANCA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Clermont', 'FRANCA', 'EUROPA', utc_timestamp);

insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Red Bull Salzburg', 'AUSTRIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Sturm Graz', 'AUSTRIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('LASK', 'AUSTRIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Hartberg', 'AUSTRIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('SK Rapid', 'AUSTRIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Austria Vienna', 'AUSTRIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Wolfsberger', 'AUSTRIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Altach', 'AUSTRIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('BW Linz', 'AUSTRIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Tirol', 'AUSTRIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Austria Lustenau', 'AUSTRIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Austria Klagenfurt', 'AUSTRIA', 'EUROPA', utc_timestamp);

insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Slavia Praga', 'REPUBLICA_CHECA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Sparta Praga', 'REPUBLICA_CHECA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Plzen', 'REPUBLICA_CHECA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Ostrava', 'REPUBLICA_CHECA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Mlada Boleslav', 'REPUBLICA_CHECA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Slovacko', 'REPUBLICA_CHECA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Liberec', 'REPUBLICA_CHECA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Sigma Olomouc', 'REPUBLICA_CHECA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Hradec Kralove', 'REPUBLICA_CHECA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Teplice', 'REPUBLICA_CHECA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Bohemians', 'REPUBLICA_CHECA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Jablonec', 'REPUBLICA_CHECA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Pardubice', 'REPUBLICA_CHECA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Zlin', 'REPUBLICA_CHECA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Karvina', 'REPUBLICA_CHECA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Ceske Budejovice', 'REPUBLICA_CHECA', 'EUROPA', utc_timestamp);

insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('M. Tel Aviv', 'ISRAEL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('M. Haifa', 'ISRAEL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('H. Beer Sheva', 'ISRAEL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('H. Haifa', 'ISRAEL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Maccabi Bnei Raina', 'ISRAEL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Sakhnin', 'ISRAEL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Hapoel Jerusalem', 'ISRAEL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('M. Petach Tikva', 'ISRAEL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Netanya', 'ISRAEL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Hapoel Hadera', 'ISRAEL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('H. Tel Aviv', 'ISRAEL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('B. Jerusalem', 'ISRAEL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Ashdod', 'ISRAEL', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('H. Petah Tikva', 'ISRAEL', 'EUROPA', utc_timestamp);

insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Molde', 'NORUEGA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Bodo/Glimt', 'NORUEGA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Kristiansund', 'NORUEGA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Lilleström', 'NORUEGA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Rosenborg', 'NORUEGA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Brann', 'NORUEGA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Fredrikstad', 'NORUEGA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Odd Grenland', 'NORUEGA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Viking', 'NORUEGA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Haugesund', 'NORUEGA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Strömsgodset', 'NORUEGA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('KFUM Oslo', 'NORUEGA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('HamKam', 'NORUEGA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Tromsö', 'NORUEGA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Sandefjord', 'NORUEGA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Sarpsborg 08', 'NORUEGA', 'EUROPA', utc_timestamp);

insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('FCSB', 'ROMENIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Rapid Bucuresti', 'ROMENIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('CFR Cluj', 'ROMENIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Univ. Craiova', 'ROMENIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Farul Constanta', 'ROMENIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Sepsi Sf. Gheorghe', 'ROMENIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('U. Cluj', 'ROMENIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('UTA Arad', 'ROMENIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('FC Hermannstadt', 'ROMENIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Petrolul', 'ROMENIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Otelul', 'ROMENIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Poli Iasi', 'ROMENIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('U. Craiova 1948', 'ROMENIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Din. Bucuresti', 'ROMENIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('FC Voluntari', 'ROMENIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Botosani', 'ROMENIA', 'EUROPA', utc_timestamp);

insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Al-Hilal', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Al-Nassr', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Al-Ahli', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Al-Ittihad', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Al-Taawoun', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Al-Ettifaq', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Al-Fateh', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Damac', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Al-Fayha', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Al-Khaleej', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Al-Shabab', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Al-Wehda', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Al-Raed', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Al-Riyadh', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Abha', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Al-Okhdood', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Al-Tai', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Al-Hazem', 'ARABIA_SAUDITA', 'ASIA', utc_timestamp);

insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Celtic', 'ESCOCIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Rangers', 'ESCOCIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Hearts', 'ESCOCIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Kilmarnock', 'ESCOCIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('St. Mirren', 'ESCOCIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Dundee FC', 'ESCOCIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Hibernian', 'ESCOCIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Motherwell', 'ESCOCIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Aberdeen', 'ESCOCIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('St. Johnstone', 'ESCOCIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Ross County', 'ESCOCIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Livingston', 'ESCOCIA', 'EUROPA', utc_timestamp);

insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Crvena zvezda', 'SERVIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Partizan', 'SERVIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('TSC', 'SERVIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Vojvodina', 'SERVIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Radnicki 1923', 'SERVIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Cukaricki', 'SERVIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Mladost', 'SERVIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Napredak', 'SERVIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Novi Pazar', 'SERVIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Radnički Nis', 'SERVIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Javor', 'SERVIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Sp. Subotica', 'SERVIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('FK Voždovac', 'SERVIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('IMT Novi Beograd', 'SERVIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Zeleznicar Pancevo', 'SERVIA', 'EUROPA', utc_timestamp);
insert into TIME (nome, pais_enum, continente_enum, data_atualizacao)  values ('Radnik', 'SERVIA', 'EUROPA', utc_timestamp);

#https://bcrypt-generator.com/naorecuperared
insert into USER (id, nome, email, senha) values (1, 'Douglas', 'douglas_d1994@hotmail.com', '$2a$12$/DuVO1ekj3ZVnWqEszglN.rb0uHetOADSJalTZ8KXonq6ZByqNBpe');
	
insert into BANCA (id, nome, id_user, valor, principal) values (1, 'Principal', 1, 1800.0, 1);
	
insert into METODO (id, nome, stake_default, id_banca, exigir_preenchimento_flag_mandante_visitante) values
	(1, 'Back Favorito', 1000, 1, 1), 
	(2, 'Lay pior em campo', 500, 1, 1), 
	(3, 'Dieguito', 100, 1, 0), 
	(4, 'Over limite', 50, 1, 0);
	
